name: random_quote_app
description: A simple Flutter app that fetches random quotes from an API

publish_to: 'none' 

environment:
  sdk: ">=3.7.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
